### ISSUE TITLE
There is a typo in YYMemoryCache.h

### ISSUE THREAD

**Issue by SeanChense** [ibireme/YYCache#1]
Your work is so fantastic.  

Line 21:It use LRU (least-recently-used) to remove objects; NSCache's eviction method is non-deterministic.

It should be It uses balabala.
:)

**Comment by ibireme** [comment]
Thanks~ I will correct it~~

**Comment by SeanChense** [comment]
Another typo in YYMemoryCache.m

Line 56
>  A **linkd** map used by YYMemoryCache.

You missed e :(

@ibireme

**Comment by ibireme** [comment]
Opps😅
Thanks again ~
