### ISSUE TITLE
[YYKVStorage] initWithPath should return error when directory already exists

### ISSUE THREAD

**Issue by skyline75489** [ibireme/YYCache#10]
The file creation part from YYKVStorage.m:

```objective-c
    NSError *error = nil;
    if (![[NSFileManager defaultManager] createDirectoryAtPath:path
                                   withIntermediateDirectories:YES
                                                    attributes:nil
                                                         error:&error] ||
        ![[NSFileManager defaultManager] createDirectoryAtPath:[path stringByAppendingPathComponent:kDataDirectoryName]
                                   withIntermediateDirectories:YES
                                                    attributes:nil
                                                         error:&error] ||
        ![[NSFileManager defaultManager] createDirectoryAtPath:[path stringByAppendingPathComponent:kTrashDirectoryName]
                                   withIntermediateDirectories:YES
                                                    attributes:nil
                                                         error:&error]) {
        NSLog(@"YYKVStorage init error:%@", error);
        return nil;
    }
```

[This will *not* result in an error if directory already exists](https://stackoverflow.com/questions/6125819/is-there-a-safer-way-to-create-a-directory-if-it-does-not-exist).

**Comment by ibireme** [comment]
When something is stored in the file directory and you may re-open it at the next time, so it should not return error.

**Comment by skyline75489** [comment]
Yet if we use `[[YYCache alloc] initWithName:@"com.me.cache"];` twice with the same name, the database will malfunction because of sqlite lock:

```plaintext
Keyboard[2373:38138] -[YYKVStorage _dbUpdateAccessTimeWithKey:] line:230 sqlite update error (5): database is locked
2015-12-02 12:47:52.458 Keyboard[2373:38079] -[YYKVStorage _dbSaveWithKey:value:fileName:extendedData:] line:216 sqlite insert error (5): database is locked
```

**Comment by ibireme** [comment]
Yes, it will make the storage unstable, see these comments:

https://github.com/ibireme/YYCache/blob/master/YYCache/YYDiskCache.h#L148
https://github.com/ibireme/YYCache/blob/master/YYCache/YYKVStorage.h#L99
https://github.com/ibireme/YYCache/blob/master/YYCache/YYCache.h#L58
https://github.com/ibireme/YYCache/blob/master/YYCache/YYCache.h#L69

**Comment by skyline75489** [comment]
I didn't really notice those comments until now...I think it would better to error out or something like that.

**Comment by ibireme** [comment]
Yeah..maybe I should give an error..
I will consider it later.

**Comment by kharmabum** [comment]
What is the recommended usage? A random NSUUID().UUIDString as the name on each run? If so we should manually delete the old disk cache correct?

**Comment by ibireme** [comment]
Currently, I recommend to create only one YYCache/YYDiskCache instance for a specified path in your app (singleton).

I will do some improvements to avoid this issues.

**Comment by ibireme** [comment]
Updated:

If the disk cache instance for the specified path already exists in memory, the initialize method will return it directly, instead of creating a new instance.
