### ISSUE TITLE
请问为什么要用CFMutableDictionaryRef而不用NSMutableDictionary？

### ISSUE THREAD

**Issue by xuzhongping** [ibireme/YYCache#112]
你好前辈，我简单测试了一下发现NSMutableDictionary的性能是优于CFMutableDictionaryRef，而且线程安全你已经在YYMemoryCache中手动设置了，所以在这两者之间你为何会选择CFMutableDictionaryRef？求解？

**Comment by xuzhongping** [comment]
除了防止非字符串的key没遵守NSCopy协议，还有别的因素吗？？

**Comment by li6185377** [comment]
性能

**Comment by xuzhongping** [comment]
貌似主要原因还是因为防止key没遵守NSCopy协议，性能的区别并不是很大，甚至有时候还不如NSMutableDictionary
