### ISSUE TITLE
取出缓存为空

### ISSUE THREAD

**Issue by JLLJHD** [ibireme/YYCache#130]
YYCache *cache = [[YYCache alloc] initWithName:JoyHomeUserCacheName];
  NSDictionary *userDic = (NSDictionary *)[cache objectForKey:JoyHomeUserModelCache];
缓存成功后 有时候取出数据为空

**Comment by nobbSir** [comment]
是因为缓存的是字典的缘故吧，我也出现过 缓存的数据结构是字典，取出为空的情况

**Comment by JLLJHD** [comment]
> 是因为缓存的是字典的缘故吧，我也出现过 缓存的数据结构是字典，取出为空的情况

是的是的  怎么解决啊

**Comment by yiimoney** [comment]
> YYCache *cache = [[YYCache alloc] initWithName:JoyHomeUserCacheName];
> NSDictionary *userDic = (NSDictionary *)[cache objectForKey:JoyHomeUserModelCache];
> 缓存成功后 有时候取出数据为空

这个问题解决了吗？

**Comment by JLLJHD** [comment]
> > YYCache *cache = [[YYCache alloc] initWithName:JoyHomeUserCacheName];
> > NSDictionary *userDic = (NSDictionary *)[cache objectForKey:JoyHomeUserModelCache];
> > 缓存成功后 有时候取出数据为空
> 
> 这个问题解决了吗？

**Comment by JLLJHD** [comment]
没有解决 楼主不回复 @panliangjie

**Comment by mzying2013** [comment]
问题是否已经解决？或者你们用其它框架替换了吗？
