### ISSUE TITLE
因为其他App占用内存过多，导致当前App被系统杀掉后，存储的信息全部丢失？

### ISSUE THREAD

**Issue by pikacode** [ibireme/YYCache#147]
你好，我们App每次在被系统杀掉以后，再启动，就获取不到缓存信息了。但是如果用户自己杀掉App再启动就是正常的。是因为我使用有误吗？

**Comment by mushanlianshi** [comment]
> 你好，我们App每次在被系统杀掉以后，再启动，就获取不到缓存信息了。但是如果用户自己杀掉App再启动就是正常的。是因为我使用有误吗？

你好，你解决了吗？ 我这边也遇到被杀，缓存信息获取不到的问题。
