### ISSUE TITLE
YYDiskCache initWithPath 存储和取值存在问题

### ISSUE THREAD

**Issue by Nododo** [ibireme/YYCache#151]
代码如图：

![yycache](https://user-images.githubusercontent.com/10458305/68365930-f95def00-016c-11ea-8b80-35fe8297d8c7.jpeg)

**Comment by ZengWeiJun** [comment]
将cache对象作为成员变量，以你图片中的处理方式，由于YYDiskCache内部没有在异步线程中hold住cache实例，因此你这里函数栈结束后，cache实例被释放，而异步操作的线程位于cache实例的成员队列_queue，_queue随着cache实例一起释放，因此你上边的存储操作过程并没有成功

建议：
如果你是存这种简单的数据可以考虑使用NSUserDefaults或者Keychain，如果必须使用YYDiskCache有两种做法
1.将方法改为同步方法，不要使用一部调用的方法
2.将cache实例保留住，不让其释放(比如成员变量或者static变量等)

**Comment by zengweijun** [comment]
YYDiskCache实例被释放了，内部这里self被释放掉，在外面保留cache实例才能解决这个问题

`- (void)removeObjectForKey:(NSString *)key completed:(void (^)(NSString * _Nonnull))completedBlock {
    __weak typeof(self) _self = self;
    dispatch_async(_queue, ^{
        __strong typeof(_self) self = _self;  // 这里self是nil，并没有执行后边的逻辑
        [self removeObjectForKey:key];
        if (completedBlock) completedBlock(key);
    });
}`

**Comment by gengcong1991** [comment]
我也遇到这个问题了，求作者解答下

**Comment by Nododo** [comment]
> 我也遇到这个问题了，求作者解答下

https://github.com/ibireme/YYCache/issues/151#issuecomment-567010958

**Comment by zengweijun** [comment]
在外面保存一下cache的实例，也可以直接使用单例对象




| |
曾维俊
|
|
邮箱：niuszeng@163.com
|

签名由 网易邮箱大师 定制

在2020年04月21日 13:41，一个小朋友 写道：

我也遇到这个问题了，求作者解答下

#151 (comment)
