### ISSUE TITLE
你好,咨询一个问题~

### ISSUE THREAD

**Issue by Nododo** [ibireme/YYCache#16]
请问YYCache能否存储大量照片,把所有的照片压缩成zip,然后上传到服务器?

**Comment by ibireme** [comment]
YYCache 存任何数据都可以。

但是压缩图片、上传服务器这就不是 Cache 的工作了。

**Comment by Nododo** [comment]
我的意思是用YYCache存储到本地的数据是否可以直接压缩还是要还原成图片再进行压缩?
就是说多图片的存储格式是多图片存储到一个文件夹还是?
我独自可以进行压缩.

**Comment by ibireme** [comment]
这取决于你的配置。

YYDiskCache 有个属性 inlineThreshold，默认值是 20480 (20K)，如果一个对象序列化后的数据大于这个值，那这个数据会单独保存为一个文件，否则会直接存入 SQLite。如果你需要把所有数据都单独存成文件，那可以把这个值设为 0。

另外，如果你需要一个图片缓存，可以参考下这个文件： https://github.com/ibireme/YYWebImage/blob/master/YYWebImage/YYImageCache.h

**Comment by Nododo** [comment]
好的，我其实想问的是能不能把一个创建一个文件夹，然后存很多张图片。。。

**Comment by Nododo** [comment]
向一个文件夹添加图片是不是要取出所有图片，然后把需要新添加的图片加进去，然后再存储？
有没有一个文件夹直接append的这种方法。。。
没表述清楚，见谅~

**Comment by ibireme** [comment]
iOS 上文件和文件夹的操作和电脑上一样。。
你可以用模拟器来测试，然后查看对应 cache 的文件。
