### ISSUE TITLE
exception  on iOS 7.0.4 iPhone5 when debuging 

### ISSUE THREAD

**Issue by Hearnseu** [ibireme/YYCache#18]
as below:
![](http://ww4.sinaimg.cn/large/7f627b2bgw1ezivbqw095j219y0sqdx9.jpg)

on iOS above 9.0, everything is ok

**Comment by ibireme** [comment]
It seems that you want to archive `URLResponseCache` object and the `NSKeyedArchiver` throws an error. You may use `[NSKeyedArchiver archivedDataWithRootObject:yourObject]` to test and log this error.
