### ISSUE TITLE
缓存

### ISSUE THREAD

**Issue by lilin87788** [ibireme/YYCache#19]
有没有办法设置一些受保护的缓存文件，
后台清除过期文件的的时候，这些文件就算过期了（ageLimit），也避免被清除
因为 现在缓存的清除 完全是自动的

**Comment by ibireme** [comment]
嗯。。现在没有这个功能。。

**Comment by lilin87788** [comment]
有这2 个需求就好了
第一 我想获取本地缓存的 存在的时间
第二 我想根据我给YYCache的时间（duration） 和 和缓存存在的时间 来判断缓存是不是有效

**Comment by ibireme** [comment]
呃，cache 对外的接口没有暴露这个属性，你可能需要先 fork 来自己改一下了。。

我还是希望对外 API 尽可能简洁，所以要再考虑下这个属性有没有必要暴露给调用者。

**Comment by lilin87788** [comment]
恩 谢谢了 ，我先关掉 这个 issue

**Comment by Saraca** [comment]
还是希望加个缓存到期可以不自动清除的功能，标记下缓存是否有效就好。
