### ISSUE TITLE
有个语法错误

### ISSUE THREAD

**Issue by RobinChao** [ibireme/YYCache#2]
> -(NSMutableArray *)_dbGetItemWithKeys:(NSArray *)keys excludeInlineData:(BOOL)excludeInlineData 方法中SQL语句

> where key in (%@);

in 中的参数如果是字符串，需要单引号，否则stmt会失败。

**Comment by ibireme** [comment]
感谢指出，明天我改一下～

**Comment by ibireme** [comment]
已修复，也避免了SQL注入

**Comment by RobinChao** [comment]
Very   Good!!
