### ISSUE TITLE
用数据库存储的时候，有没有数据迁移问题？

### ISSUE THREAD

**Issue by yufenglv** [ibireme/YYCache#26]

**Comment by ibireme** [comment]
这里面的 SQLite 表结构很简单，没有变动过而且未来也应该不会改变了，所以没有什么迁移问题。

**Comment by yufenglv** [comment]
好的，多谢 ~

**Comment by ibireme** [comment]
SQLite 只存储一些元数据（key、time、size 等）和少量比较小的 value，所以总数据量不会很大。SQLite 开启了 WAL 模式，写入速度不会太慢；查询语句也都是有索引的。
