### ISSUE TITLE
如何实现一个页面一张表，以及关联查询功能

### ISSUE THREAD

**Issue by ShaochongDu** [ibireme/YYCache#27]
如题，因为如果不同页面数据都放在一张表的话，key值有可能会有重复，所以想每个页面建一张表用于区分；同时，请问题如果放在了不同表中，如果进行访问；或者能不能以多个键值作为联合key检索数据

**Comment by ibireme** [comment]
这只是 Cache，每个 Cache 只支持简单的 Key-Value 存储和查询（类似 NSDictionary）。如果需要支持更复杂的数据结构或查询条件，那还是推荐直接用 FMDB/Realm/CoreData 之类的库。
