### ISSUE TITLE
多线程读的时候会crash？

### ISSUE THREAD

**Issue by yufenglv** [ibireme/YYCache#29]
我改了下demo，用并发线程进行读的时候会crash
写的时候sqlite有文件锁，是正常的。

**Comment by ibireme** [comment]
能写一下使用的版本、相关代码、崩溃日志或崩溃代码位置吗？

**Comment by yufenglv** [comment]
![Uploading 屏幕快照 2016-02-29 上午10.34.54.png…]()
![Uploading 屏幕快照 2016-02-29 上午10.35.19.png…]()

**Comment by yufenglv** [comment]
用的是master的代码
[代码截图](https://github.com/yufenglv/yufenglv.github.io/blob/master/images/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202016-02-29%20%E4%B8%8A%E5%8D%8810.35.19.png)
[crash 截图](https://github.com/yufenglv/yufenglv.github.io/blob/master/images/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202016-02-29%20%E4%B8%8A%E5%8D%8810.30.17.png)

**Comment by yufenglv** [comment]
测试代码   
 dispatch_queue_t queue = dispatch_queue_create("com.test",  DISPATCH_QUEUE_CONCURRENT);
    for(int i = 0; i < 10; ++i){
        dispatch_async(queue, ^{
            NSTimeInterval begin, end, time;
            begin = CACurrentMediaTime();
            @autoreleasepool {
                for (int i = 0; i < 10000; i++) {
                    YYKVStorageItem *item = [yykvSQLite getItemForKey:keys[i]];
                    NSNumber *value = [NSKeyedUnarchiver unarchiveObjectWithData:item.value];
                    if (!value) printf("error!");
                }
            }
            end = CACurrentMediaTime();
            time = end - begin;
            printf("YYKVSQLite:   %8.2f\n", time * 1000);
        });
    }

**Comment by ibireme** [comment]
这个是测试 YYKVStorage 的代码，这个类不是线程安全的，注释已经给了 warning：https://github.com/ibireme/YYCache/blob/master/YYCache/YYKVStorage.h#L71-L74

需要线程安全的话，用 YYDiskCache，它对 YYKVStorage 进行了封装，提供了足够简单的接口和线程安全的保障。

**Comment by yufenglv** [comment]
了解了，多谢回答 ~

**Comment by yufenglv** [comment]
你好，再请教下，看代码dickcache是用信号量来加锁，sqlite的读本身不是支持并发的吗？是因为读的时候要更新accessTime，所以才加锁的吗？

**Comment by ibireme** [comment]
sqlite 本身只存储一些属性（key/size/filename/accesstime等）和数据量较小的 value，其他大部分数据都是保存成单独的文件的，这部分读写要加锁来避免数据不同步。另外每次访问 sqlite 时，读操作大都会跟着写操作，所以即使支持了读并发也提高不了什么效率吧。

**Comment by yufenglv** [comment]
恩，多谢 ~
