### ISSUE TITLE
今天看了 下 “YYKVStorage”类，请教几个问题。

### ISSUE THREAD

**Issue by zhenyiyi** [ibireme/YYCache#33]
1. "- (sqlite3_stmt *)_dbPrepareStmt:(NSString *)sql "
     执行这个函数时候，拿到 “sqlite3_stmt” stmt 时候，为什么要执行 sqlite3_reset(stmt)？

2.  在执行完 “ sqlite3_step(stmt)” 时， 为什么有时候不执行 “sqlite3_finalize(stmt)”？
    比如执行 “- (BOOL)_dbUpdateAccessTimeWithKey:(NSString *)key”
    我看了部分文档，介绍说要执行的。

3.  为什么我们执行“remove...”操作后，要执行 “sqlite3_wal_checkpoint(_db, NULL)” 。
     我们每次删除的是“-wal”文件的内容吗，删除完 要同步下数据库吗？

**Comment by ibireme** [comment]
1. _dbPrepareStmt 返回的可能是一个缓存下来的 stmt，所以用之前需要先 reset 一下。
2. `_dbUpdateAccessTimeWithKeys` 这里面的 stmt 是一次性的，使用完后就销毁了，并没有用到缓存。
3. 执行 checkpoint 的地方，是 removeItemsLargerThanXXX 等方法，一般外部在调用这几个方法时，通常是需要缩小存储占用空间，这时把 wal 日志文件同步回 sqlite 主数据库，会减少 wal 文件的此盘占用。另外，默认情况下，sqlite 也会在某些时间点自动执行 checkpoint 的。
