### ISSUE TITLE
请教几个问题

### ISSUE THREAD

**Issue by wws19125** [ibireme/YYCache#34]
1、看到内存缓存用的是双向链表，请问这么做只是用来按照时间排序的么？
2、cost值其实没看懂，请问cost是什么意思呢，看到赋值为0？

**Comment by ibireme** [comment]
1. Dictionary 配合双向链表，用于实现 LRU 淘汰算法。双向链表里的对象是按访问时间排序的。
2. cost 只是个可选的参数，用来表示对象的消耗（大小、体积、宽高等等），如果调用者不关心这个参数，那就设置为 0。

**Comment by wws19125** [comment]
好吧，基本和我想的一致。双向链除了实现LRU算法，还有其他作用么，比如内存效率上的提升？

**Comment by ibireme** [comment]
没有其他作用。如果这里不用 LRU，那就没必要用双向链表了。

**Comment by wws19125** [comment]
tks
