### ISSUE TITLE
关于在 removeObjectForKey 释放 node 的问题

### ISSUE THREAD

**Issue by SeanChense** [ibireme/YYCache#4]
if (node) {
        [_lru removeNode:node];
        _YYLinkedMapNode *node = [_lru removeTailNode];
        if (_lru->_releaseAsynchronously) {
            dispatch_queue_t queue = _lru->_releaseOnMainThread ? dispatch_get_main_queue() : YYMemoryCacheGetReleaseQueue();
            dispatch_async(queue, ^{
                [node class]; //hold and release in queue
            });
        } else if (_lru->_releaseOnMainThread && !pthread_main_np()) {
            dispatch_async(dispatch_get_main_queue(), ^{
                [node class]; //hold and release in queue
            });
        }
    }

我最近在学习 iOS 的内存管理知识，这个地方我有一些不解，想请教一下您。
`_YYLinkedMapNode *node = [_lru removeTailNode];` 这里的 node 是被注册到了 autoreleasepool 吧？

在接下来的 dispatch_async GCD 操作是为了什么呢？
不是会有 ARC 来帮助自动 release 没有用的内存么？

还是说想根据自定义的需求，指定在某个线程下完成释放？但是在 autoreleasepool 中的释放并不是立即进行的么？

**Comment by ibireme** [comment]
node 会被 block 捕获，随后会在 block 结束后，在对应的 queue 里得到释放。
[node class]; 这条语句，只是为了让 node 捕获到 block 去，所以随便发了个消息以避免被编译器优化掉。

**Comment by SeanChense** [comment]
@ibireme 谢谢啦。

**Comment by zdrjson** [comment]
1.如果不写gcd，方法块执行完后，编译器会立刻释放掉对象？
2.为什么holder对象应该根据配置在不同线程进行释放(release)？这个技术你是怎么学习到的？

**Comment by wangdetong** [comment]
请问：为什么要强调让 node去指定的queue去释放，让编译器优化掉会有什么问题吗？

**Comment by wangdetong** [comment]
我测了一下怎么不好使呢？看代码：
```objc
    YYTestReleaseQueue *model = [[YYTestReleaseQueue alloc] init];
    if (model) {
        dispatch_queue_t queue = dispatch_get_global_queue(0, 0);
        dispatch_async(queue, ^{
        NSLog(@"dealloc at %@",[NSThread currentThread]);
            [model class]; // release in queue
        });
    }

```

```objc
#import "YYTestReleaseQueue.h"

@implementation YYTestReleaseQueue


- (void)dealloc
{
    NSLog(@"dealloc at %@",[NSThread currentThread]);
}
@end
```
