### ISSUE TITLE
YYDiskCache 再次初始化的时候，会清除原有数据

### ISSUE THREAD

**Issue by pylee** [ibireme/YYCache#42]
作者你好，在使用YYDiskCache时，再次初始化YYDiskCache，传入原有路径会清除原有数据？这种情况如何再次初始化原有路径的老数据呢？或者有其他使用方法？谢谢。

**Comment by ibireme** [comment]
正常情况下是不会清除数据的。你可以测试一下 YYKit 中的图片 Demo，网络图片在底层是被缓存到 YYDiskCache 的，再次打开 App 图片还在的。

大概有几种情况下缓存会被清除：
1. 设置了 `countLimit`、`costLimit`、`ageLimit` 并达到了限额。
2. sqlite 数据库损坏无法读取
3. 磁盘空间不够，iOS 系统主动清空缓存文件夹。

**Comment by pylee** [comment]
这个情况有点奇怪，因为我分了几处使用YYDiskCache这个来保存不同的数据，有的没有问题，再次初始化数据能拿出来，有的就不行，因为我看了文件夹下面的manifest.sqlite（用sqlitebrowser查看）在初始化前还有旧数据，运行了initWithPath过后，再看就为空了，所以最后我在使用时就拿到nil的对象。

1. 没有设置过 countLimit、costLimit、ageLimit，这些都是默认值
2. _**sqlite数据库不知道怎么判断是否损坏**_
3. 磁盘空间应该够，我在模拟器上试的。
4. 这期间没有调用过remove方法

**Comment by ibireme** [comment]
这就不太清楚了，可能需要具体调试一下。。

试试改一下 YYDiskCache.m，在 `YYKVStorage *kv = [[YYKVStorage alloc] initWithPath:path type:type];` 之后，设置一下 `kv.errorLogsEnabled = YES;` 看看是否有什么错误日志。

另外，如果传入相同的 cache name 或 path 来初始化 YYDiskCache，并且内存中已经有同名/同路径的实例，那就会直接返回那个对应实例，用来保证对于每个 path 最多只有一个实例来进行操作。不清楚这个会不会影响到你的代码逻辑。

**Comment by pylee** [comment]
已找到原因，是我自己的失误造成的，多谢楼主的热心回复。😄
