### ISSUE TITLE
把YYCache文件夹拖入项目中报Ambiguous use of 'objectForKey'错误

### ISSUE THREAD

**Issue by heeween** [ibireme/YYCache#45]
大神,写demo调试好了,现在拖入工程中就会报这个错误 ,为什么呢
![image](https://cloud.githubusercontent.com/assets/12106605/15035153/268e4ee2-12b1-11e6-8db0-d3004b58faa4.png)

**Comment by ibireme** [comment]
首先检查 Xcode 版本是否是最新版本。

之后检查项目代码中是否有相同方法从而造成冲突，再检查下这块儿的类型推断是否有问题。

**Comment by heeween** [comment]
这是IQKeyboardManagerSwift的代码 是跟IQKeyboardManagerSwift冲突了么

**Comment by heeween** [comment]
现在几乎是最新的了xcode了 昨天发布了7.3.1 我更新试下

**Comment by ibireme** [comment]
private var textFieldInfoCache = NSMutableSet()
    
    for infoDict in textFieldInfoCache {
    
        if let view = infoDict.objectForKey(kIQTextField) as? UIView {
            updateReturnKeyTypeOnTextField(view)
        }
    }

<img width="380" alt="2016-05-06 12 07 46" src="https://cloud.githubusercontent.com/assets/839283/15048991/9bbc4ea4-131e-11e6-8908-aa6febb0d397.png">

首先这个 textFieldInfoCache 不支持范性，然后在 for in 的时候，取出的 infoDict 应该是无法推断类型的。此时调用了 objectForKey，Xcode 应该会根据这个方法全局搜索，确定参数和返回类型的唯一性。引入 YYCache 时，这个猜测就会有歧义了。

其实如果你只引入 IQKeyboard，然后随便新建一个类，加一个 `objectForKey:` 的方法并返回一个有明确类型的对象，这个也会在这里报错，很容易验证。这里应该明确指定 infoDict 的类型。

**Comment by heeween** [comment]
明白了 方法名相同的问题 NSSet里面元素又无法推断类型
