### ISSUE TITLE
锁的选择

### ISSUE THREAD

**Issue by feiadan** [ibireme/YYCache#50]
MemoryCache中用pthread_mutex_lock锁，
DiskCache中对数据库操作部分用的GCD的信号量。

请问为什么这样选择的？有什么原则吗？

**Comment by ibireme** [comment]
嗯。。开始的时候 MemoryCache 用了 OSSpinLock，后来换成的 pthread_mutex。没什么特别的意思。。

**Comment by feiadan** [comment]
好吧，那就是没什么选择的原则了。

**Comment by eggswift** [comment]
@feiadan "OSSpinLock is unsafe unless you can guarantee that all users have the same priority." 我猜是因为这个原因. 作者关于这个写了: http://blog.ibireme.com/2016/01/16/spinlock_is_unsafe_in_ios/?utm_source=tuicool&utm_medium=referral
