### ISSUE TITLE
关于加密

### ISSUE THREAD

**Issue by ZS1314** [ibireme/YYCache#57]
感觉YYCache写的非常棒，尤其是非常简洁。可是，YYCache存储需要加密的数据时，如何处理呢？

**Comment by ibireme** [comment]
目前只能在外部先加密好再进行存储了。

**Comment by ZS1314** [comment]
现在我遇到一个问题，我们加密使用的aes加密，我们把要存储的数据转换成data在转成json字串进行存储，可是NSJSONSerialization似乎并不支持NSDate格式的数据，会引起线程崩溃，有比较好的解决方案或者方向吗

**Comment by ibireme** [comment]
是的，JSON 只支持 Array Dictionary Number String Null 几种数据类型。Data 可以用 base64 等方法转换为 String 再来传输。

**Comment by ZS1314** [comment]
感谢，我目前就是这么处理的
