### ISSUE TITLE
https://github.com/ibireme/YYCache/blob/master/YYCache/YYKVStorage.m#L847-L849 返回值疑惑

### ISSUE THREAD

**Issue by SinCheung** [ibireme/YYCache#59]
https://github.com/ibireme/YYCache/blob/master/YYCache/YYKVStorage.m#L847-L849 
这里移除早于某个时间的file和mixed类型的返回判断应该是YES吧，这里写成了NO。

**Comment by ibireme** [comment]
感谢指出，确实应该是 YES（好在没有影响现有逻辑）。

Fixed: https://github.com/ibireme/YYCache/commit/b4002953c756f6c054602a8532cbc7b3ac7547f4

**Comment by SinCheung** [comment]
能阅读到高质量的代码，受教了。
