### ISSUE TITLE
Example of use

### ISSUE THREAD

**Issue by dingua** [ibireme/YYCache#6]
Can you please provide an example for how to use YYCache ?

**Comment by ibireme** [comment]
Here's an example in another project: https://github.com/ibireme/YYWebImage/blob/master/YYWebImage/YYImageCache.h

**Comment by hanluner** [comment]
大神，作为初学者，我也挺期待能够有个较为完整的示例项目，这样可能更有助于理解使用。

**Comment by SummerYP** [comment]
网络数据缓存如何使用YYCache，大神能提供一个demo吗
