### ISSUE TITLE
存取出现空的情况

### ISSUE THREAD

**Issue by wyhazq** [ibireme/YYCache#62]
- setObject: forKey: withBlock:
- objectForKey: withBlock:

使用的是以上两个方法，下面的没问题，不知道作者有没有遇到过。

- setObject: forKey:
- objectForKey:

**Comment by wyhazq** [comment]
没事了。。。是下午写代码写到傻逼了。。。

**Comment by d553296416** [comment]
怎么解决的，我也遇到了

**Comment by wyhazq** [comment]
withBlock:是异步，检查下代码，当时写懵了出错了。。。
