### ISSUE TITLE
缓存过期时间的问题

### ISSUE THREAD

**Issue by baight** [ibireme/YYCache#63]
我查看了一下DiskCache的ageLimit属性，它的工作原理大概是：我每取一次缓存，这个缓存的 last_access_time 就会更新；当 last_access_time 到 现在的时间  > ageLimit 时，该缓存就会被清理。

然而，这并不是我期待的缓存过期清理功能。
我所期待的是，我保存这个缓存的时间 到 现在的时间 > limit 时，该缓存就会被清理。

这样的需求很常见，我对某个接口做缓存，这个缓存只能用两天，两天后我就需要重新调接口，以便获取最新的数据。（并不能因为我在这两天内使用了该缓存，就导致该缓存一直有效）。

望增加一个这样的功能～
^_^

（我二了，才看到之前已经有人提过这样的功能了，我又重复提了。
不过，我还是再提一遍吧，因为我觉得这个功能还挺常用的。
看到你说，这样一个功能可能会限制它存取效率。不过我觉得，大多数人（其实就是我）根本不太在乎效率，只要说得过去就行；我们更在乎它好用不好用。
如果真的要追求极致的效率，可能通过预编译啊什么的，来开启或关闭这样的功能）

**Comment by ibireme** [comment]
只是说和已有的方法和概念有些冲突吧，所以不太好改。
