### ISSUE TITLE
YYCache 取数据方面有一个性能上的疑问.

### ISSUE THREAD

**Issue by zhangchioulin** [ibireme/YYCache#74]
感谢ibireme提供了 YYKit 这套解决方案给我们,谢谢. 我在使用的时候有些疑问.

1. 假如说我想取出20条数据,我自己搭建的 SQLite 数据库我能一次性取出这20条数据的 resultSet 集合,然后在统一遍历添加到可变数组当中. 但是 YYCache 取出的数据是一条的,就需要对数据库先查询一条在取出来,然后插入数据中.如此反复20次. 这样难免会造成性能损耗, 请问该怎么解决?
2. 如果上面的方法用"放一整个数据的集合到数据库中"解决的话,不太好.
3. 我能否直接访问 YYCache 的数据库,做只查询操作?
4. YYCache 是否能支持 key "<" ">" 的查询而不仅限于"="?

提出以上问题,是因为我在做项目的离线缓存,如果ibireme有别的利用 YYCache 实现的离线缓存方法可否告知一下?

**Comment by ibireme** [comment]
现在所有的方法都是封装好的，没有对外暴露太多底层和复杂的接口。。。所以实现的话可能要修改 YYDiskCache、YYKVStorage 来添加方法了。。

如果只用 YYKVStorage 的话，倒是有批量存取的接口。

**Comment by zhangchioulin** [comment]
thx
