### ISSUE TITLE
小小的问题

### ISSUE THREAD

**Issue by lovesunstar** [ibireme/YYCache#8]
如图：

![image](https://cloud.githubusercontent.com/assets/2378280/11267824/8562364c-8ee8-11e5-9eac-aa682d70a023.png)

第一个红色的框应该直接return nil; 或者调用 initWithName: nil
第二个红色的框应该直接删掉

可以参照：
https://developer.apple.com/library/ios/documentation/General/Conceptual/DevPedia-CocoaCore/MultipleInitializers.html

不过没什么问题，哈哈，就是偶尔扫了一眼

**Comment by ibireme** [comment]
如果不调用 super 的 NS_DESIGNATED_INITIALIZER 方法，编译器会有警告，所以这里只好这么写了。。

另外，在头文件里，已经标记了这两个方法是不可用的，所以这两个方法实际上永远不会被调用到：

    - (instancetype)init UNAVAILABLE_ATTRIBUTE;
    + (instancetype)new UNAVAILABLE_ATTRIBUTE;

**Comment by lovesunstar** [comment]
嗯。

警告的话，你可以通过指定新的 NS_DESIGNTED_INITIALIZER 来解决。

**Comment by ibireme** [comment]
也是，改了一下～
