### ISSUE TITLE
关于数据库查询不方便的问题

### ISSUE THREAD

**Issue by spWang** [ibireme/YYCache#85]
1.数据库操作是否可以提供分页查询的功能,例如
+ (NSArray <id>*)objectsWithPage:(NSInteger)page pageCount(NSInteger)pageCount;

2.如果我存的是model对象,例如model有个属性是age,目前是把model归档后存为二进制的,如果我查询数据库,想查age大于20的,目前这样的缓存用起来还不是很方便,有什么好的办法

**Comment by li6185377** [comment]
这种需求不适合使用缓存， 你要直接存数据库

**Comment by spWang** [comment]
有道理

**Comment by spWang** [comment]
还有,  是否可以增加个过期时间的控制

**Comment by SpaceStar2016** [comment]
YYCache没有批量查询的操作吗？我看了一下，YYKVS有一个方法：
- (NSArray *)getItemInfoForKeys:(NSArray *)keys {
    if (keys.count == 0) return nil;
    return [self _dbGetItemWithKeys:keys excludeInlineData:YES];
}
但是您好像没有用上去？请问是什么原因呢？
